import jsPDF from 'jspdf'

export function generateReportPdf(caseData) {
  const { id, prediction, scanner, group, age, sex } = caseData
  const flagged = prediction >= 0.5
  const flagColor = flagged ? [176, 65, 62] : [47, 111, 94]   // matches --color-flag-positive / negative
  const mutedColor = [107, 107, 104]

  const doc = new jsPDF({ unit: 'pt', format: 'letter' })
  const marginX = 56
  let y = 64

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(28, 29, 31)
  doc.text('Case Report', marginX, y)

  y += 18
  doc.setFont('courier', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...mutedColor)
  doc.text(id, marginX, y)

  y += 28
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(...flagColor)
  doc.text(
    `${flagged ? 'PDAC likely' : 'PDAC unlikely'} — ${(prediction * 100).toFixed(1)}% predicted probability`,
    marginX, y
  )

  y += 30
  const rows = [
    ['Prediction', `${(prediction * 100).toFixed(1)}%`],
    ['Scanner', scanner],
    ['Referral pathway', group],
    ['Age / Sex', `${age} / ${sex}`],
  ]

  doc.setFontSize(10)
  rows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...mutedColor)
    doc.text(label, marginX, y)
    doc.setFont('courier', 'normal')
    doc.setTextColor(28, 29, 31)
    doc.text(String(value), marginX + 180, y)
    doc.setDrawColor(228, 227, 223)
    doc.line(marginX, y + 6, 500, y + 6)
    y += 24
  })

  y += 20
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...mutedColor)
  const disclaimer =
    'This report is generated by an AI-assisted detection model and is intended to support, ' +
    'not replace, clinical judgment. Prediction confidence should be interpreted alongside ' +
    'the referral pathway and imaging findings.'
  const wrapped = doc.splitTextToSize(disclaimer, 460)
  doc.text(wrapped, marginX, y)

  doc.save(`${id}_report.pdf`)
}