import jsPDF from 'jspdf'

async function imageDataUrl(url) {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`Unable to load report image (${response.status})`)
  const blob = await response.blob()
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onloadend = () => resolve(reader.result)
    reader.onerror = () => reject(new Error('Unable to read report image'))
    reader.readAsDataURL(blob)
  })
}

export async function addReportImages(doc, caseData, apiBase, startY = 20) {
  const base = apiBase.replace(/\/+$/, '')
  const paths = [
    caseData.ct_slices?.base_path && `${base}/${caseData.ct_slices.base_path.replaceAll('\\', '/')}/slice_${caseData.ct_slices.mid_slice ?? 0}.png`,
    caseData.gradcam_path && `${base}/${caseData.gradcam_path.replaceAll('\\', '/')}`,
    caseData.segmentation_path && `${base}/${caseData.segmentation_path.replaceAll('\\', '/')}`,
  ].filter(Boolean)
  let y = startY
  for (const [index, path] of paths.entries()) {
    const image = await imageDataUrl(path)
    if (y > 245) {
      doc.addPage()
      y = 20
    }
    doc.setFontSize(10)
    doc.text(['Preprocessed CT scan', 'Grad-CAM', 'Segmented pancreas boundary'][index], 14, y)
    doc.addImage(image, 'PNG', 14, y + 4, 80, 60)
    y += 72
  }
}

export function generateReportPdf(caseData) {
  const { id, prediction, group, age, sex } = caseData
  const flagged = prediction >= 0.5
  const flagColor = flagged ? [176, 65, 62] : [47, 111, 94]   // matches --color-flag-positive / negative
  const mutedColor = [107, 107, 104]

  const doc = new jsPDF({ unit: 'pt', format: 'letter' })
  const marginX = 56
  let y = 64

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(28, 29, 31)
  doc.text('Case Report', marginX, y)

  y += 18
  doc.setFont('courier', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...mutedColor)
  doc.text(id, marginX, y)

  y += 28
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(...flagColor)
  doc.text(
    `${flagged ? 'PDAC likely' : 'PDAC unlikely'} — ${(prediction * 100).toFixed(1)}% predicted probability`,
    marginX, y
  )

  y += 30
  const rows = [
    ['Prediction', `${(prediction * 100).toFixed(1)}%`],
    ['Referral pathway', group],
    ['Age / Sex', `${age} / ${sex}`],
  ]

  doc.setFontSize(10)
  rows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...mutedColor)
    doc.text(label, marginX, y)
    doc.setFont('courier', 'normal')
    doc.setTextColor(28, 29, 31)
    doc.text(String(value), marginX + 180, y)
    doc.setDrawColor(228, 227, 223)
    doc.line(marginX, y + 6, 500, y + 6)
    y += 24
  })

  y += 20
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...mutedColor)
  const disclaimer =
    'This report is generated by an AI-assisted detection model and is intended to support, ' +
    'not replace, clinical judgment. Prediction confidence should be interpreted alongside ' +
    'the referral pathway and imaging findings.'
  const wrapped = doc.splitTextToSize(disclaimer, 460)
  doc.text(wrapped, marginX, y)

  doc.save(`${id}_report.pdf`)
}